# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anagram.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Anagram(object):
    def setupUi(self, Anagram):
        Anagram.setObjectName("Anagram")
        Anagram.resize(200, 330)
        Anagram.setMinimumSize(QtCore.QSize(200, 330))
        Anagram.setMaximumSize(QtCore.QSize(360, 330))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Assets/Assets/letter-v-button-of-square-shape-with-one-rounded-corner (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Anagram.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Anagram)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 200, 60))
        self.label.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Times New Roman\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.jword = QtWidgets.QLabel(self.centralwidget)
        self.jword.setGeometry(QtCore.QRect(10, 70, 180, 41))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.jword.setFont(font)
        self.jword.setStyleSheet("font: 16pt \"Century\";")
        self.jword.setAlignment(QtCore.Qt.AlignCenter)
        self.jword.setWordWrap(True)
        self.jword.setObjectName("jword")
        self.input = QtWidgets.QTextEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 130, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(10, 210, 91, 51))
        self.submit_button.setStyleSheet("font: 14pt \"Georgia\";")
        self.submit_button.setObjectName("submit_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(10, 260, 181, 51))
        self.exit_button.setStyleSheet("font: 14pt \"Georgia\";")
        self.exit_button.setObjectName("exit_button")
        self.Next_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Next_Button.setGeometry(QtCore.QRect(100, 210, 91, 51))
        self.Next_Button.setStyleSheet("font: 14pt \"Georgia\";")
        self.Next_Button.setObjectName("Next_Button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 180, 30))
        self.label_3.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        Anagram.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Anagram)
        self.statusbar.setObjectName("statusbar")
        Anagram.setStatusBar(self.statusbar)

        self.retranslateUi(Anagram)
        QtCore.QMetaObject.connectSlotsByName(Anagram)

    def retranslateUi(self, Anagram):
        _translate = QtCore.QCoreApplication.translate
        Anagram.setWindowTitle(_translate("Anagram", "Anagram"))
        self.label.setText(_translate("Anagram", "ANAGRAM"))
        self.jword.setText(_translate("Anagram", "TextLabel"))
        self.input.setStatusTip(_translate("Anagram", "Enter Correct word"))
        self.input.setHtml(_translate("Anagram", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.input.setPlaceholderText(_translate("Anagram", "Guess the Word"))
        self.submit_button.setStatusTip(_translate("Anagram", "Check"))
        self.submit_button.setText(_translate("Anagram", "Check"))
        self.exit_button.setText(_translate("Anagram", "Exit"))
        self.Next_Button.setStatusTip(_translate("Anagram", "Next"))
        self.Next_Button.setText(_translate("Anagram", "Next"))
        self.label_3.setText(_translate("Anagram", "RESULT"))
import Main_rc
